spring:
  datasource:
    url: jdbc:mysql://10.10.10.105:3306/oos?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: oos
    password: 12345678
    
    
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
mybatis:
  config-location: classpath:mybatis-config.xml 
  
  mapper-locations: classpath:/mapper/*.xml
  

    
