spring:
  datasource:
    url: jdbc:mysql://10.10.10.105/oos?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: oos
    password: 12345678
 
  servlet:
    multipart:
      max-file-size: 20971520
      max-request-size: 41943040
      file-size-threshold: 20971520
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8080
